# Generated by Django 5.1 on 2026-02-10 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('sql_query', models.TextField(verbose_name='Requête SQL')),
                ('visibility', models.CharField(choices=[('private', 'Privé'), ('public', 'Public')], default='private', max_length=10, verbose_name='Visibilité')),
                ('output_types', models.JSONField(blank=True, default=list, help_text='Liste des types de sortie autorisés (CSV, XLSX, PDF, JSON, XML)', verbose_name='Types de sortie')),
                ('routing_modes', models.JSONField(blank=True, default=list, help_text='Modes de routage autorisés (screen, email, sftp, ftp, local)', verbose_name='Modes de routage')),
                ('csv_separator', models.CharField(default=',', max_length=5, verbose_name='Séparateur CSV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_reports', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Paramètres')),
                ('output_type', models.CharField(max_length=10, verbose_name='Type de sortie')),
                ('routing_mode', models.CharField(max_length=20, verbose_name='Mode de routage')),
                ('routing_config', models.JSONField(blank=True, default=dict, verbose_name='Configuration routage')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échoué')], default='pending', max_length=10, verbose_name='Statut')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Démarré à')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='report_results/%Y/%m/%d/', verbose_name='Fichier résultat')),
                ('error_message', models.TextField(blank=True, default='', verbose_name="Message d'erreur")),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.report', verbose_name='Rapport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_executions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Exécution de rapport',
                'verbose_name_plural': 'Exécutions de rapports',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_execute', models.BooleanField(default=False, verbose_name='Peut exécuter')),
                ('can_modify', models.BooleanField(default=False, verbose_name='Peut modifier')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_permissions', to='auth.group', verbose_name='Groupe')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='reports.report', verbose_name='Rapport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Permission de rapport',
                'verbose_name_plural': 'Permissions de rapport',
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Paramètres')),
                ('output_type', models.CharField(max_length=10, verbose_name='Type de sortie')),
                ('routing_mode', models.CharField(max_length=20, verbose_name='Mode de routage')),
                ('routing_config', models.JSONField(blank=True, default=dict, verbose_name='Configuration routage')),
                ('schedule_type', models.CharField(choices=[('once', 'Une fois'), ('recurring', 'Récurrent')], default='once', max_length=10, verbose_name='Type de planification')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'exécution prévue")),
                ('cron_expression', models.CharField(blank=True, default='', max_length=100, verbose_name='Expression cron')),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50, verbose_name='Fuseau horaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID tâche Celery Beat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.report', verbose_name='Rapport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Planification de rapport',
                'verbose_name_plural': 'Planifications de rapports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du paramètre')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('param_type', models.CharField(choices=[('string', 'Texte'), ('number', 'Nombre'), ('date', 'Date'), ('datetime', 'Date/Heure'), ('enum', 'Énumération'), ('boolean', 'Booléen')], default='string', max_length=20, verbose_name='Type')),
                ('operators', models.JSONField(blank=True, default=list, help_text='Liste des opérateurs autorisés pour ce paramètre', verbose_name='Opérateurs')),
                ('default_value', models.CharField(blank=True, default='', max_length=500, verbose_name='Valeur par défaut')),
                ('required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('enum_values', models.JSONField(blank=True, default=list, help_text='Valeurs possibles pour le type enum', verbose_name='Valeurs enum')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='reports.report', verbose_name='Rapport')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'ordering': ['order', 'id'],
                'unique_together': {('report', 'name')},
            },
        ),
    ]
