# Generated by Django 5.1 on 2026-02-10 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='settings_app.datasource', verbose_name='Source de données'),
        ),
    ]
