# Generated by Django 5.1 on 2026-04-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Finance', 'Finance'), ('industrie', 'Industrie'), ('distribution', 'Distribution'), ('Taiwan', 'Taiwan')], max_length=50, null=True, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='report',
            name='email_body',
            field=models.TextField(blank=True, default='', help_text="Corps du message lors de l'envoi par email", verbose_name="Corps de l'email"),
        ),
    ]
