# Generated by Django 5.1 on 2026-04-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_category_report_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='email_body_footer',
            field=models.TextField(blank=True, default='', help_text='Texte affiché après le tableau des résultats (signature)', verbose_name='Signature / Texte de fin email'),
        ),
        migrations.AddField(
            model_name='report',
            name='email_body_header',
            field=models.TextField(blank=True, default='', help_text="Texte affiché avant le tableau des résultats dans l'email", verbose_name="Texte d'introduction email"),
        ),
        migrations.AddField(
            model_name='report',
            name='embed_results',
            field=models.BooleanField(default=False, help_text="Si activé, les résultats seront insérés en tant que tableau HTML dans le corps de l'email", verbose_name="Intégrer les résultats dans l'email"),
        ),
    ]
