services:
  redis:
    image: redis:7-alpine
    container_name: fastreport-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: postgres:15-alpine
    container_name: fastreport-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fastreport}
      POSTGRES_USER: ${POSTGRES_USER:-fastreport_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mot_de_passe_fort}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-fastreport_user} -d ${POSTGRES_DB:-fastreport}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastreport-backend
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput --clear 2>/dev/null;
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload --timeout 120 --workers 2"
    volumes:
      - ./backend:/app
      - media_data:/app/media
    ports:
      - "8001:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastreport-celery-worker
    command: celery -A config worker -l INFO --concurrency=2
    volumes:
      - ./backend:/app
      - media_data:/app/media
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastreport-celery-beat
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./backend:/app
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fastreport-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_PROXY_TARGET=http://backend:8000
      - NODE_OPTIONS=--dns-result-order=ipv4first
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  redis_data:
  media_data:
  postgres_data:
