# Generated by Django 5.1 on 2026-02-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('oracle', 'Oracle'), ('sqlserver', 'SQL Server')], max_length=20, verbose_name='Type de base')),
                ('host', models.CharField(max_length=255, verbose_name='Hôte')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('database_name', models.CharField(max_length=255, verbose_name='Nom de la base')),
                ('username', models.CharField(max_length=255, verbose_name='Utilisateur')),
                ('password', models.CharField(max_length=500, verbose_name='Mot de passe')),
                ('options', models.JSONField(blank=True, default=dict, help_text='Paramètres de connexion supplémentaires (JSON)', verbose_name='Options')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Source de données',
                'verbose_name_plural': 'Sources de données',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('protocol', models.CharField(choices=[('ftp', 'FTP'), ('sftp', 'SFTP')], default='sftp', max_length=4, verbose_name='Protocole')),
                ('host', models.CharField(max_length=255, verbose_name='Hôte')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('username', models.CharField(max_length=255, verbose_name='Utilisateur')),
                ('password', models.CharField(blank=True, default='', max_length=500, verbose_name='Mot de passe')),
                ('remote_path', models.CharField(default='/', max_length=500, verbose_name='Chemin distant')),
                ('is_default', models.BooleanField(default=False, verbose_name='Par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration FTP/SFTP',
                'verbose_name_plural': 'Configurations FTP/SFTP',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SmtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('host', models.CharField(max_length=255, verbose_name='Serveur SMTP')),
                ('port', models.IntegerField(default=587, verbose_name='Port')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Utilisateur')),
                ('password', models.CharField(blank=True, default='', max_length=500, verbose_name='Mot de passe')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Adresse expéditeur')),
                ('is_default', models.BooleanField(default=False, verbose_name='Par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration SMTP',
                'verbose_name_plural': 'Configurations SMTP',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
